Hw 2 2
Balkosha78/HomeWork-2-2 pull request #1
Opened 2023-04-01 06:47 UTC by Balkosha78

2023-04-01 18:46 UTC, alekseykoshelev requested changes

2023-04-01 18:46 UTC, alekseykoshelev commented on src/Hogwarts.java
> +    private int powerOfMagic;  // сила магии
Тут можно еще добавить строковое поле с именем

2023-04-01 18:46 UTC, alekseykoshelev commented on src/Hogwarts.java
> +        return this.powerOfMagic + this.transgress;
Этот метод хороший, а вот метод на 21 строке непонятный, думаю, можно оставить только этот метод

2023-04-01 18:46 UTC, alekseykoshelev commented on src/Student.java
> +    private Hogwarts hogwarts;
В целом идея с этим классом интересная, но неудобно будет использовать тип Hogwarts. В данной домашке нужно сделать 4 методы, которые принимают разных учеников.

2023-04-01 18:46 UTC, alekseykoshelev commented on src/Main.java
> +        if (facStudent1.getClass() == facStudent2.getClass()) {
Это вот как раз тот неудобный момент, в будущих уроках узнаем как можно делать. В этой домашке все же требуется через 4 метода сделать)

2023-04-02 01:14 UTC, Balkosha78 commented
После просмотра разбора, я понял как должно быть все просто и быстро. Я долго ходил около )) Старею.

2023-04-03 15:20 UTC, merged